AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Micronaut API - my.service::my-service
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  MyServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: example.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/distributions/api-proxy-example-0.1.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MyServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/ping'
    Export:
      Name: MyServiceApi
